### ISSUE TITLE
你好，运行demo.py时发生错误，如何解决啊，急求回复。

### ISSUE THREAD

**Issue by feixiaoyu2223** [Qidian213/deep_sort_yolov3#103]
Using TensorFlow backend.
/home/wr506/anaconda3/envs/flyfly_py2/lib/python3.5/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "demo.py", line 113, in <module>
    main(YOLO())
  File "/home/wr506/Documents/flyfly/deep_sort_qidian_22/yolo.py", line 33, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "/home/wr506/Documents/flyfly/deep_sort_qidian_22/yolo.py", line 54, in generate
    self.yolo_model = load_model(model_path, compile=False)
  File "/home/wr506/anaconda3/envs/flyfly_py2/lib/python3.5/site-packages/keras/models.py", line 246, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/wr506/anaconda3/envs/flyfly_py2/lib/python3.5/site-packages/keras/models.py", line 314, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/home/wr506/anaconda3/envs/flyfly_py2/lib/python3.5/site-packages/keras/layers/__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "/home/wr506/anaconda3/envs/flyfly_py2/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 140, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/wr506/anaconda3/envs/flyfly_py2/lib/python3.5/site-packages/keras/engine/topology.py", line 2450, in from_config
    process_layer(layer_data)
  File "/home/wr506/anaconda3/envs/flyfly_py2/lib/python3.5/site-packages/keras/engine/topology.py", line 2419, in process_layer
    custom_objects=custom_objects)
  File "/home/wr506/anaconda3/envs/flyfly_py2/lib/python3.5/site-packages/keras/layers/__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "/home/wr506/anaconda3/envs/flyfly_py2/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 142, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/home/wr506/anaconda3/envs/flyfly_py2/lib/python3.5/site-packages/keras/engine/topology.py", line 1242, in from_config
    return cls(**config)
  File "/home/wr506/anaconda3/envs/flyfly_py2/lib/python3.5/site-packages/keras/layers/advanced_activations.py", line 38, in __init__
    self.alpha = K.cast_to_floatx(alpha)
  File "/home/wr506/anaconda3/envs/flyfly_py2/lib/python3.5/site-packages/keras/backend/common.py", line 108, in cast_to_floatx
    return np.asarray(x, dtype=_FLOATX)
  File "/home/wr506/.local/lib/python3.5/site-packages/numpy/core/numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: float() argument must be a string or a number, not 'dict'

**Comment by gyc521zsc** [comment]
> Using TensorFlow backend.
> /home/wr506/anaconda3/envs/flyfly_py2/lib/python3.5/site-packages/h5py/**init**.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
> from ._conv import register_converters as _register_converters
> Traceback (most recent call last):
> File "demo.py", line 113, in 
> main(YOLO())
> File "/home/wr506/Documents/flyfly/deep_sort_qidian_22/yolo.py", line 33, in **init**
> self.boxes, self.scores, self.classes = self.generate()
> File "/home/wr506/Documents/flyfly/deep_sort_qidian_22/yolo.py", line 54, in generate
> self.yolo_model = load_model(model_path, compile=False)
> File "/home/wr506/anaconda3/envs/flyfly_py2/lib/python3.5/site-packages/keras/models.py", line 246, in load_model
> model = model_from_config(model_config, custom_objects=custom_objects)
> File "/home/wr506/anaconda3/envs/flyfly_py2/lib/python3.5/site-packages/keras/models.py", line 314, in model_from_config
> return layer_module.deserialize(config, custom_objects=custom_objects)
> File "/home/wr506/anaconda3/envs/flyfly_py2/lib/python3.5/site-packages/keras/layers/**init**.py", line 54, in deserialize
> printable_module_name='layer')
> File "/home/wr506/anaconda3/envs/flyfly_py2/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 140, in deserialize_keras_object
> list(custom_objects.items())))
> File "/home/wr506/anaconda3/envs/flyfly_py2/lib/python3.5/site-packages/keras/engine/topology.py", line 2450, in from_config
> process_layer(layer_data)
> File "/home/wr506/anaconda3/envs/flyfly_py2/lib/python3.5/site-packages/keras/engine/topology.py", line 2419, in process_layer
> custom_objects=custom_objects)
> File "/home/wr506/anaconda3/envs/flyfly_py2/lib/python3.5/site-packages/keras/layers/**init**.py", line 54, in deserialize
> printable_module_name='layer')
> File "/home/wr506/anaconda3/envs/flyfly_py2/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 142, in deserialize_keras_object
> return cls.from_config(config['config'])
> File "/home/wr506/anaconda3/envs/flyfly_py2/lib/python3.5/site-packages/keras/engine/topology.py", line 1242, in from_config
> return cls(**config)
> File "/home/wr506/anaconda3/envs/flyfly_py2/lib/python3.5/site-packages/keras/layers/advanced_activations.py", line 38, in **init**
> self.alpha = K.cast_to_floatx(alpha)
> File "/home/wr506/anaconda3/envs/flyfly_py2/lib/python3.5/site-packages/keras/backend/common.py", line 108, in cast_to_floatx
> return np.asarray(x, dtype=_FLOATX)
> File "/home/wr506/.local/lib/python3.5/site-packages/numpy/core/numeric.py", line 501, in asarray
> return array(a, dtype, copy=False, order=order)
> TypeError: float() argument must be a string or a number, not 'dict'

I meet this problem.Do you solve this?

**Comment by xlj199** [comment]
Using TensorFlow backend.
Traceback (most recent call last):
  File "D:\Adaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\Adaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Adaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\Adaconda\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "D:\Adaconda\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 13, in <module>
    from yolo import YOLO
  File "E:\1\deep_sort_yolov3\yolo.py", line 14, in <module>
    from keras import backend as K
  File "D:\Adaconda\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "D:\Adaconda\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "D:\Adaconda\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "D:\Adaconda\lib\site-packages\keras\backend\__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "D:\Adaconda\lib\site-packages\keras\backend\load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "D:\Adaconda\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "D:\Adaconda\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "D:\Adaconda\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "D:\Adaconda\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "D:\Adaconda\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "D:\Adaconda\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\Adaconda\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "D:\Adaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "D:\Adaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\Adaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Adaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\Adaconda\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "D:\Adaconda\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 找不到指定的模块。


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
