### ISSUE TITLE
convert.py Unsupported section header type: 'reorg_0' and 'region_0'

### ISSUE THREAD

**Issue by juanmanuelrq** [Qidian213/deep_sort_yolov3#151]
Hi

When I use:
python convert.py yolo-obj.cfg yolo-obj_final.weights model_data/yolo.h5

I have this error:
`Traceback (most recent call last): File "convert.py", line 266, in <module> _main(parser.parse_args()) File "convert.py", line 239, in _main 'Unsupported section header type: {}'.format(section)) ValueError: Unsupported section header type: reorg_0`

and I add these lines

```
        elif section.startswith('reorg_0'):
            pass
        elif section.startswith('region_0'):
            pass
```
 but the result was
```
Saved Keras model to model_data/yolo_sdm.h5
Read 48850214 of 50619686.0 from Darknet weights.
Warning: 1769472.0 unused weights

```

**Comment by ZERO-SPACE-X** [comment]
I have the same error. Could you share your solution?

**Comment by rsek147** [comment]
You should use `yolov3.cfg` and `yolov3.weights` instead of `yolo-obj.cfg`
