### ISSUE TITLE
UnboundLocalError: local variable 'track' referenced before assignment

### ISSUE THREAD

**Issue by khush12** [Qidian213/deep_sort_yolov3#168]
while running, i am facing this issue:
Traceback (most recent call last):
  File "/content/deep_sort_yolov3/demo.py", line 170, in <module>
    main(YOLO())
  File "/content/deep_sort_yolov3/demo.py", line 158, in main
    if len(pts[track.track_id]) != None:
UnboundLocalError: local variable 'track' referenced before assignment

**Comment by aizuon** [comment]
same here

**Comment by tkone2018** [comment]
do you solve it ? i met the problem too

**Comment by strangevaleera** [comment]
me too
