### ISSUE TITLE
h5py.h5f.open IOError

### ISSUE THREAD

**Issue by ShaBoiJimmy** [Qidian213/deep_sort_yolov3#63]
TERMINAL:

`python demo.py
Using TensorFlow backend.
2018-11-19 03:04:27.991850: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:865] ARM64 does not support NUMA - returning NUMA node zero
2018-11-19 03:04:27.992063: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: NVIDIA Tegra X2 major: 6 minor: 2 memoryClockRate(GHz): 1.3005
pciBusID: 0000:00:00.0
totalMemory: 7.66GiB freeMemory: 494.86MiB
2018-11-19 03:04:27.992136: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2018-11-19 03:04:30.366888: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-19 03:04:30.367020: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2018-11-19 03:04:30.367076: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2018-11-19 03:04:30.367384: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 91 MB memory) -> physical GPU (device: 0, name: NVIDIA Tegra X2, pci bus id: 0000:00:00.0, compute capability: 6.2)
Traceback (most recent call last):
  File "demo.py", line 112, in <module>
    main(YOLO())
  File "/home/nvidia/Desktop/Shane and Jason/YoloV3/deep_sort_yolov3/yolo.py", line 33, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "/home/nvidia/Desktop/Shane and Jason/YoloV3/deep_sort_yolov3/yolo.py", line 54, in generate
    self.yolo_model = load_model(model_path, compile=False)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/saving.py", line 417, in load_model
    f = h5dict(filepath, 'r')
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/io_utils.py", line 186, in __init__
    self.data = h5py.File(path, mode=mode)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (file signature not found)`

How to I get the IOError to go away? Has anyone encountered this before?

Thanks

**Comment by Totoro-wen** [comment]
hello.I have the same problem.I would certainly be interested to hear how you got on?
