### ISSUE TITLE
error "The name 'net/images:0' refers to a Tensor which does not exist"

### ISSUE THREAD

**Issue by VellalaVineethKumar** [Qidian213/deep_sort_yolov3#78]
i have retrained yolo for custom objects (by Alexey AB) and i have the corresponding weights file and cfg file after training is completed
i converted these to .h5 file using convert.py file provided by you
and now when i run demo.py i get 
shashwat@udayWorkstation:~/Desktop/vineeth/deep_sort_yolov3-master$ python demo.py 
Using TensorFlow backend.
tf.estimator package not installed.
tf.estimator package not installed.
2019-01-03 20:01:54.879294: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-01-03 20:01:54.885631: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2019-01-03 20:01:54.885680: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: udayWorkstation
2019-01-03 20:01:54.885687: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: udayWorkstation
2019-01-03 20:01:54.885721: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 396.54.0
2019-01-03 20:01:54.885746: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 396.54.0
2019-01-03 20:01:54.885753: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 396.54.0
model_data/yolo.h5 model, anchors, and classes loaded.
Traceback (most recent call last):
  File "demo.py", line 114, in <module>
    main(YOLO())
  File "demo.py", line 32, in main
    encoder = gdet.create_box_encoder(model_filename,batch_size=1)
  File "/home/shashwat/Desktop/vineeth/deep_sort_yolov3-master/tools/generate_detections.py", line 100, in create_box_encoder
    image_encoder = ImageEncoder(model_filename, input_name, output_name)
  File "/home/shashwat/Desktop/vineeth/deep_sort_yolov3-master/tools/generate_detections.py", line 81, in __init__
    "net/%s:0" % input_name)
  File "/home/shashwat/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3666, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/home/shashwat/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3490, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/shashwat/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3532, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'net/images:0' refers to a Tensor which does not exist. The operation, 'net/images', does not exist in the graph."
@Qidian213 please help

**Comment by ss199302** [comment]
@VellalaVineethKumar  Can you solve this problem? How to solve it?

**Comment by xjhjinhui** [comment]
@ss199302 There may be problems with tensorflow, cuda, cudnn versions.My versions are 1.4.0, 8.0, 6.0, respectively.

**Comment by YinRui1991** [comment]
Delete 'net/' in 'net/images', this is caused by higher tf version
